"""Initial Migiration

Revision ID: fd5440b530e8
Revises: 
Create Date: 2025-02-18 14:21:44.246114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd5440b530e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('naics', sa.Integer(), nullable=False),
    sa.Column('newexist', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('createjob', sa.Integer(), nullable=False),
    sa.Column('franchisecode', sa.Integer(), nullable=False),
    sa.Column('revline', sa.Integer(), nullable=False),
    sa.Column('lowdoc', sa.Integer(), nullable=False),
    sa.Column('grappv', sa.Integer(), nullable=False),
    sa.Column('sbaappv', sa.Integer(), nullable=False),
    sa.Column('urbanrural', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('loan_requests')
    # ### end Alembic commands ###
