"""Initial Migiration

Revision ID: 057f6e4b12b8
Revises: 
Create Date: 2025-02-19 16:02:52.209992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '057f6e4b12b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NAICS', sa.Integer(), nullable=False),
    sa.Column('UrbanRural', sa.Integer(), nullable=False),
    sa.Column('LowDoc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_loan_float', sa.Float(), nullable=False),
    sa.Column('SBA_loan_float', sa.Float(), nullable=False),
    sa.Column('FranchiseCode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('BankState', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('RevLineCr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Term', sa.Integer(), nullable=False),
    sa.Column('crisis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('loan_requests')
    # ### end Alembic commands ###
