"""Initial Migiration

Revision ID: 1c5f1f0ac46a
Revises: fd5440b530e8
Create Date: 2025-02-19 12:04:00.836800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c5f1f0ac46a'
down_revision: Union[str, None] = 'fd5440b530e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_requests', 'accepted')
    # ### end Alembic commands ###
