"""Ajout/modification des tables

Revision ID: 691143f98a2f
Revises: 057f6e4b12b8
Create Date: 2025-02-24 11:39:41.598182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '691143f98a2f'
down_revision: Union[str, None] = '057f6e4b12b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('GrAppv', sa.Float(), nullable=False))
    op.add_column('loan_requests', sa.Column('NAICS_Sectors', sa.Integer(), nullable=False))
    op.add_column('loan_requests', sa.Column('New', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('loan_requests', sa.Column('Franchise', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('loan_requests', sa.Column('NoEmp', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('loan_requests', sa.Column('Rural', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('loan_requests', sa.Column('PIF', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('loan_requests', 'NAICS')
    op.drop_column('loan_requests', 'SBA_loan_float')
    op.drop_column('loan_requests', 'UrbanRural')
    op.drop_column('loan_requests', 'crisis')
    op.drop_column('loan_requests', 'FranchiseCode')
    op.drop_column('loan_requests', 'bank_loan_float')
    op.drop_column('loan_requests', 'Bank')
    op.drop_column('loan_requests', 'BankState')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('BankState', sa.VARCHAR(), nullable=False))
    op.add_column('loan_requests', sa.Column('Bank', sa.VARCHAR(), nullable=False))
    op.add_column('loan_requests', sa.Column('bank_loan_float', sa.FLOAT(), nullable=False))
    op.add_column('loan_requests', sa.Column('FranchiseCode', sa.VARCHAR(), nullable=False))
    op.add_column('loan_requests', sa.Column('crisis', sa.INTEGER(), nullable=False))
    op.add_column('loan_requests', sa.Column('UrbanRural', sa.INTEGER(), nullable=False))
    op.add_column('loan_requests', sa.Column('SBA_loan_float', sa.FLOAT(), nullable=False))
    op.add_column('loan_requests', sa.Column('NAICS', sa.INTEGER(), nullable=False))
    op.drop_column('loan_requests', 'PIF')
    op.drop_column('loan_requests', 'Rural')
    op.drop_column('loan_requests', 'NoEmp')
    op.drop_column('loan_requests', 'Franchise')
    op.drop_column('loan_requests', 'New')
    op.drop_column('loan_requests', 'NAICS_Sectors')
    op.drop_column('loan_requests', 'GrAppv')
    # ### end Alembic commands ###
